# Generated by Django 5.2.12 on 2026-03-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevo_analytics', '0007_brevoemail_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brevoemail',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Blacklist Management', 'verbose_name_plural': 'Blacklist Management'},
        ),
        migrations.AlterModelOptions(
            name='brevomessage',
            options={'ordering': ['-sent_at', '-sent_date', 'subject'], 'verbose_name': 'Message Analysis', 'verbose_name_plural': 'Message Analysis'},
        ),
        migrations.AddField(
            model_name='brevomessage',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, help_text="Chiave stabile di raggruppamento (es. 'digest:747'). Se presente, il lookup usa group_key+sent_date invece di subject+sent_date.", max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='brevomessage',
            index=models.Index(fields=['group_key', 'sent_date'], name='brevo_messa_group_k_89043b_idx'),
        ),
        migrations.AddConstraint(
            model_name='brevomessage',
            constraint=models.UniqueConstraint(condition=models.Q(('group_key__isnull', False)), fields=('group_key', 'sent_date'), name='unique_brevo_message_group_key_date'),
        ),
    ]
