# Generated by Django 5.2.16 on 2026-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevo_analytics', '0008_alter_brevoemail_options_alter_brevomessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brevomessage',
            name='total_bounced_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brevomessage',
            name='total_bounced_soft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brevomessage',
            name='total_bounced_undetermined',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brevomessage',
            name='total_deferred',
            field=models.IntegerField(default=0),
        ),
    ]
